package: cropper
version: '1.0.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cropper

pages:
    mediapool/cropper:
        title: cropper
        hidden: true
        pjax: true

requires:
    redaxo: '^5.5' # benötigt mindestens REDAXO 5.5
    packages:
        media_manager: '^2.0.1'
    php:
        version: '>=5.6'
        extensions: [gd]

conflicts:
    packages:
        media_manager: '>=3'
