package: cropper
version: '3.0.6'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cropper

page:
    title: 'translate:cropper_settings_title'
    icon: rex-icon fa-crop
    perm: cropper[settings]
    subpages:
        settings:
            title: "translate:cropper_settings"
pages:
    mediapool/cropper:
        title: cropper
        hidden: true
        pjax: true

requires:
    redaxo: '^5.8'
    php:
        version: '>7.4'
        extensions: [gd]

default_config:
    default_jpg_quality: 100
    default_png_compression: 9
    show_compression_settings_in_mediapool: 1
