package: cropper
version: '1.3.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cropper

pages:
    mediapool/cropper:
        title: cropper
        hidden: true
        pjax: true

requires:
    redaxo: '^5.12'
    php:
        version: '>7.3'
        extensions: [gd]
