package: cropper
version: '2.0.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cropper

page:
    title: 'translate:cropper_settings_title'
    icon: rex-icon fa-crop
    perm: cropper[settings]
    subpages:
        settings:
            title: "translate:cropper_settings"
pages:
    mediapool/cropper:
        title: cropper
        hidden: true
        pjax: true

requires:
    redaxo: '^5.8'
    php:
        version: '>7.4'
        extensions: [gd]
