package: cropper
version: '1.1.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cropper

pages:
    mediapool/cropper:
        title: cropper
        hidden: true
        pjax: true

requires:
    redaxo: '^5.8' # benötigt mindestens REDAXO 5.5
    php:
        version: '^5.6'
        extensions: [gd]
