package: cropper
version: '1.2.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/cropper

pages:
    mediapool/cropper:
        title: cropper
        hidden: true
        pjax: true

requires:
    redaxo: '^5.8'
    php:
        version: '>5.6'
        extensions: [gd]
